<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Swivel</RootNamespace>
    <AssemblyName>swivel</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
  </PropertyGroup>

</Project>